import Head from "next/head";
import type { ChildrenProps } from "../types";
import Footer from "./Footer";
import Main from "./Main";
import Modal from "./Modal";
import Nav from "./Nav";
import Sidebar from "./Sidebar";

const Layout: React.FC<ChildrenProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Hosni T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-screen px-2 pb-12 lg:px-4">
        <Nav />
        <div className="mt-4 grid min-h-screen-1/2 grid-cols-12 gap-4">
          <Main className="col-span-12 md:col-span-8 xl:col-span-9">
            {children}
          </Main>
          <Sidebar className="col-span-12 md:col-span-4 xl:col-span-3" />
        </div>
      </div>
      <Footer />
      <Modal />
    </>
  );
};

export default Layout;
